name: Generate xml sitemap

on:
  push:
    branches:
      - master

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Ping Google
      run: curl https://www.google.com/ping?sitemap=https://sapython.me/sitemap.xml
